version: 2.1
orbs:
  matlab: mathworks/matlab@0.4.0
jobs:
  build_python:
    docker:
      - image: circleci/python:3.8.5
    environment:
      CONDA_ENV_NAME: data-science
      CONDA_ENV_FILE: "./python/environment.yml"
      OUTPUT_FIGURES_FOLDER: "/tmp/figures"
    steps:
      - checkout
      - run:
          name: Update system, fetch LFS files
          command: |
            sudo apt-get update
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs fetch
      - run:
          name: Install conda
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
            chmod +x miniconda.sh
            CONDA_PATH=$HOME/miniconda
            ./miniconda.sh -b -p $CONDA_PATH
            echo "export PATH=$CONDA_PATH/bin:$PATH" >> $BASH_ENV
            echo "conda init bash" >> $BASH_ENV
      - run:
          name: "Configure and update conda"
          command: |
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
      - run:
          name: Run script
          command: |
            conda env create -n $CONDA_ENV_NAME python=$TRAVIS_PYTHON_VERSION -f $CONDA_ENV_FILE
            conda activate $CONDA_ENV_NAME
            python ./python/yearly_data_analysis.py
            mkdir $OUTPUT_FIGURES_FOLDER
            cp ./figures/* $OUTPUT_FIGURES_FOLDER/
      - store_artifacts:
          path: $OUTPUT_FIGURES_FOLDER

workflows:
  version: 2.1
  run_all_tests:
    jobs:
      - build_python
