version: 2.1
orbs:
  matlab: mathworks/matlab@0.4.0
jobs:
  build_python:
    machine:
      image: ubuntu:latest
    environment:
      - CONDA_ENV_NAME: data-science
      - CONDA_ENV_FILE: "./python/environment.yml"
      - OUTPUT_FIGURES_FOLDER: "/tmp/figures"
    steps:
      - checkout
      - run:
          name: Install conda
          command: |
            sudo apt-get update
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
            bash miniconda.sh -b -p $HOME/miniconda
            export PATH="$HOME/miniconda/bin:$PATH"
            hash -r
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
      - run:
          name: Run python
          command: |
            conda env create -n $CONDA_ENV_NAME python=$TRAVIS_PYTHON_VERSION -f $CONDA_ENV_FILE
            source activate $CONDA_ENV_NAME
            python ./python/yearly_data_analysis.py
            mkdir $OUTPUT_FIGURES_FOLDER
            cp ./figures/* $OUTPUT_FIGURES_FOLDER/
      - store_artifacts:
          path: $OUTPUT_FIGURES_FOLDER

workflows:
  version: 2.1
  run_all_tests:
    jobs:
      - build_python
